# Generated by Django 5.1.7 on 2025-07-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2025-07-13')),
                ('temperatura_media', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperatura_maxima', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperatura_minima', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('precipitacion', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('horas_hr_90', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperatura_media_hr_90', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('favorable', models.IntegerField(null=True)),
                ('severidad', models.IntegerField(null=True)),
                ('deteccion_inicial', models.IntegerField(null=True)),
                ('empresa', models.ManyToManyField(to='empresa.empresa')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacion.estacion')),
            ],
            options={
                'unique_together': {('fecha', 'estacion')},
            },
        ),
    ]
