# Generated by Django 5.1.7 on 2025-07-13 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipodealerta', models.CharField(blank=True, choices=[('No aspersión', 'No aspersión'), ('Alerta Tizón', 'Alerta Tizón'), ('Aspersión cada 7 días', 'Aspersión cada 7 días'), ('Aspersión cada 5 días', 'Aspersión cada 5 días')], max_length=30, null=True)),
                ('tipodemensaje', models.CharField(choices=[('A', 'Alerta'), ('M', 'Mensaje'), ('C', 'Consulta')], max_length=11)),
                ('recibido', models.BooleanField(default=False, verbose_name='Recibido')),
                ('img', models.FileField(blank=True, null=True, upload_to='media')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 7, 13, 13, 48, 31, 361782))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 7, 13, 13, 48, 31, 361782))),
            ],
        ),
    ]
