# Generated by Django 5.1.7 on 2025-07-13 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='remitente', to=settings.AUTH_USER_MODEL),
        ),
    ]
