# Generated by Django 5.1.7 on 2025-07-13 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 13, 55, 41, 292277)),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 13, 55, 41, 292277)),
        ),
    ]
