# Generated by Django 5.1.7 on 2025-07-14 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_alter_mensajes_created_at_alter_mensajes_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 13, 36, 58, 885567)),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 13, 36, 58, 885567)),
        ),
    ]
