# Generated by Django 5.1.7 on 2025-07-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('representante', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=30)),
                ('estacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estacion.estacion')),
            ],
        ),
    ]
